# **Fredrik EDA**

In [6]:
import pandas as pd

df = pd.read_excel("data/resultat-2024-for-kurser-inom-yh.xlsx", sheet_name="Lista ansökningar")

df.head()

,Diarienummer,Beslut,Anordnare namn,Utbildningsnamn,Utbildningsområde,Antal beviljade platser start 2024,Antal beviljade platser start och slut 2024,Antal beviljade platser start 2025,Totalt antal beviljade platser,YH-poäng,Kommun,Län,FA-region,Antal kommuner,Antal län,Antal FA-regioner
0,MYH 2024/1000,Avslag,Changemaker Educations AB,Futuregames Accessible Game Production,Juridik,0,0,0,0,25,"Se ""Lista flera kommuner""","Se ""Lista flera kommuner""","Se ""Lista flera kommuner""",3,3,3
1,MYH 2024/1001,Avslag,Changemaker Educations AB,Futuregames Inclusive Game Development,"Ekonomi, administration och försäljning",0,0,0,0,25,"Se ""Lista flera kommuner""","Se ""Lista flera kommuner""","Se ""Lista flera kommuner""",3,3,3
2,MYH 2024/1002,Avslag,Båstads kommun Akademi Båstad,Ekosystemtjänster i praktiken,"Lantbruk, djurvård, trädgård, skog och fiske",0,0,0,0,50,Båstad,Skåne,Malmö-Lund,1,1,1
3,MYH 2024/1003,Avslag,Båstads kommun Akademi Båstad,Hållbar dagvattenhantering i praktiken,"Lantbruk, djurvård, trädgård, skog och fiske",0,0,0,0,50,Båstad,Skåne,Malmö-Lund,1,1,1
4,MYH 2024/1004,Avslag,Båstads kommun Akademi Båstad,Invasiva växter i utemiljöer,"Lantbruk, djurvård, trädgård, skog och fiske",0,0,0,0,25,Båstad,Skåne,Malmö-Lund,1,1,1

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 880 entries, 0 to 879
Data columns (total 16 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   Diarienummer                                 880 non-null    object
 1   Beslut                                       880 non-null    object
 2   Anordnare namn                               880 non-null    object
 3   Utbildningsnamn                              880 non-null    object
 4   Utbildningsområde                            880 non-null    object
 5   Antal beviljade platser start 2024           880 non-null    int64
 6   Antal beviljade platser start och slut 2024  880 non-null    int64
 7   Antal beviljade platser start 2025           880 non-null    int64
 8   Totalt antal beviljade platser               880 non-null    int64
 9   YH-poäng                                     880 non-null    int64
 10  Kommun                                       880 non-null    object
 11  Län                                          880 non-null    object
 12  FA-region                                    880 non-null    object
 13  Antal kommuner                               880 non-null    int64
 14  Antal län                                    880 non-null    int64
 15  Antal FA-regioner                            880 non-null    int64
dtypes: int64(8), object(8)
memory usage: 110.1+ KB

In [10]:
df_courses = df.copy()
df_courses.head()

,Diarienummer,Beslut,Anordnare namn,Utbildningsnamn,Utbildningsområde,Antal beviljade platser start 2024,Antal beviljade platser start och slut 2024,Antal beviljade platser start 2025,Totalt antal beviljade platser,YH-poäng,Kommun,Län,FA-region,Antal kommuner,Antal län,Antal FA-regioner
0,MYH 2024/1000,Avslag,Changemaker Educations AB,Futuregames Accessible Game Production,Juridik,0,0,0,0,25,"Se ""Lista flera kommuner""","Se ""Lista flera kommuner""","Se ""Lista flera kommuner""",3,3,3
1,MYH 2024/1001,Avslag,Changemaker Educations AB,Futuregames Inclusive Game Development,"Ekonomi, administration och försäljning",0,0,0,0,25,"Se ""Lista flera kommuner""","Se ""Lista flera kommuner""","Se ""Lista flera kommuner""",3,3,3
2,MYH 2024/1002,Avslag,Båstads kommun Akademi Båstad,Ekosystemtjänster i praktiken,"Lantbruk, djurvård, trädgård, skog och fiske",0,0,0,0,50,Båstad,Skåne,Malmö-Lund,1,1,1
3,MYH 2024/1003,Avslag,Båstads kommun Akademi Båstad,Hållbar dagvattenhantering i praktiken,"Lantbruk, djurvård, trädgård, skog och fiske",0,0,0,0,50,Båstad,Skåne,Malmö-Lund,1,1,1
4,MYH 2024/1004,Avslag,Båstads kommun Akademi Båstad,Invasiva växter i utemiljöer,"Lantbruk, djurvård, trädgård, skog och fiske",0,0,0,0,25,Båstad,Skåne,Malmö-Lund,1,1,1

In [12]:
df_courses["Utbildningsområde"].value_counts()

Utbildningsområde
Ekonomi, administration och försäljning         221
Data/IT                                         157
Teknik och tillverkning                         121
Hälso- och sjukvård samt socialt arbete         109
Samhällsbyggnad och byggteknik                  105
Lantbruk, djurvård, trädgård, skog och fiske     38
Pedagogik och undervisning                       30
Hotell, restaurang och turism                    24
Säkerhetstjänster                                19
Juridik                                          18
Kultur, media och design                         18
Journalistik och information                     14
Transporttjänster                                 4
Friskvård och kroppsvård                          2
Name: count, dtype: int64

In [ ]:
import duckdb

# Antal beviljade/avslag av kurser i Sverige 2024

approved_courses = duckdb.query(
    """--sql
    SELECT
        Beslut,
        COUNT(*) AS Antal_Kursanökningar
    FROM
        df_courses
    GROUP BY Beslut
"""
).df()

approved_courses

     Beslut  Antal_Kursanökningar
0    Avslag                   429
1  Beviljad                   451

In [33]:
# Procentuellt antal beviljade

all_courses = len(df_courses)
# all_courses -- 880
approved = len(df_courses[df_courses["Beslut"] == "Beviljad"])
# approved -- 451

percent_approved = (approved / all_courses) * 100
f"{percent_approved:.2f}%"

'51.25%'

# Beviljade ansökningar per skola

In [57]:
approval_per_school = duckdb.query(
    """--sql
SELECT 
    "Anordnare namn" AS "Anordnare",
    COUNT(*) AS "Ansökta kurser",
    COUNT(*) FILTER (WHERE Beslut = 'Beviljad') AS "Antal beviljade",
    ROUND(
        COUNT(*) FILTER (WHERE Beslut = 'Beviljad') * 100.0 / COUNT(*),
        1
    ) AS "Beviljandegrad %"
FROM df
GROUP BY "Anordnare namn"
ORDER BY "Antal beviljade" DESC
""").df().set_index("Anordnare")

approval_per_school

,Ansökta kurser,Antal beviljade,Beviljandegrad %
Anordnare,,,
YH Akademin AB,45,35,77.8
IHM Business School AB Göteborg,30,27,90.0
Medieinstitutet i Sverige AB,23,19,82.6
Nackademin AB,18,18,100.0
"Göteborgs Stad, Yrgo",24,14,58.3
...,...,...,...
Dille Gård AB,1,0,0.0
Kulturama,1,0,0.0
Svenska Trädmästarna AB,1,0,0.0
Falkenbergs kommun,1,0,0.0
WeWon Media Group AB,5,0,0.0